example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name="show_xml"),
    path('json/', show_json, name="show_json"),
    path('json/<int:id>', show_json_by_id, name="show_json_by_id"),
    path('xml/<int:id>', show_xml_by_id, name="show_xml_by_id"),
    path('register/', register, name="register"),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='ajax'),
    path('ajax/submit', json_to_database_async, name='json_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
import json
from wishlist.utils import write_json
from django.shortcuts import render, redirect
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Kak Cinoy',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Kak Cinoy',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def json_to_database_async(request):
    data_from_fetch = json.load(request)

    nama_barang = data_from_fetch['nama_barang']
    harga_barang = int(data_from_fetch['harga_barang'])
    deskripsi = data_from_fetch['deskripsi']

    new_wishlist = BarangWishlist.objects.create(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)

    data = {
        "model": "wishlist.barangwishlist",
        "pk": new_wishlist.id,
        "fields":{
            "nama_barang": nama_barang,
            "harga_barang": harga_barang,
            "deskripsi": deskripsi
        }
    }

    write_json(data)
    
    return JsonResponse(data)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    if request.user.is_authenticated:
        return redirect(reverse('wishlist:show_wishlist')) 
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:ajax")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    if request.user.is_authenticated:
        return redirect(reverse('wishlist:ajax')) 
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn btn-primary" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<body class="bg-light text-white">
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <h5>Nama: {{nama}}</h5>
          <button type="button" class="btn btn-outline-dark" ><a  href="{% url 'wishlist:logout' %}"> Logout </a> </button>
        </div>
    </nav>
    
    <div class="m-5 container text-center">
        <div class="row justify-content-md-center">
            <div class="col col-lg-10">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                          <th scope="col">Nama barang</th>
                          <th scope="col">Harga Barang</th>
                          <th scope="col">Deskripsi</th>
                        </tr>
                      </thead>
                    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
                    {% for barang in list_barang %}
                        <tr>
                            <th>{{barang.nama_barang}}</th>
                            <th>{{barang.harga_barang}}</th>
                            <th>{{barang.deskripsi}}</th>
                        </tr>
                    {% endfor %}
                    </table>
            </div>
    
        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>
        {% endblock content %}
    </div>
</body>

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<title>My Wishlist</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', (e) => {
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        const myForm = document.getElementById('form-barang');
        const currentURL = window.location.href + "submit";

        myForm.addEventListener('submit', (e) => {
            e.preventDefault();

            const formData = new FormData(myForm);
            
            const nama = formData.get('nama_barang');
            const harga = formData.get('harga_barang');
            const deskripsi = formData.get('deskripsi'); 

            fetch(currentURL, {
                method: 'POST',
                credentials: 'same-origin',
                headers:{
                    'Accept': 'application/json',
                    'X-Requested-With': 'XMLHttpRequest', //Necessary to work with request.is_ajax()
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({'nama_barang': nama, 'harga_barang': harga, 'deskripsi': deskripsi})
            }).then((response) => {
                return response.json();
            }).then((json_data) => {
                const tableBody = document.getElementById('barang-wishlist');
                console.log(tableBody)
                // Insert a row at the end of table
                var newRow = tableBody.insertRow(-1);
                // Insert a cell at the end of the row
                var nama_barang_cell = newRow.insertCell();
                var harga_barang_cell = newRow.insertCell();
                var deskripsi_barang_cell = newRow.insertCell();
                // Append a text node to the cell
                var nama_barang = document.createTextNode(json_data['fields']['nama_barang']);
                var harga_barang = document.createTextNode(json_data['fields']['harga_barang']);
                var deskripsi = document.createTextNode(json_data['fields']['deskripsi']);
                nama_barang_cell.appendChild(nama_barang);
                harga_barang_cell.appendChild(harga_barang);
                deskripsi_barang_cell.appendChild(deskripsi);
            }).catch((error) => {
                console.error(error);
            })

        });
    });
</script>
{% endblock meta %}

{% block content %}

<body class="bg-light text-white">
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <h5>Nama: {{nama}}</h5>
          <button type="button" class="btn btn-outline-dark" ><a  href="{% url 'wishlist:logout' %}"> Logout </a> </button>
        </div>
    </nav>
    
    <div class="container d-flex flex-column align-items-center justify-content-center m-5">
        <h2 class="text-dark">Tambah Wishlist</h2>
        <div class="col-md-4 col-md-offset-4">
            <form method="POST" action="" id="form-barang">
                {% csrf_token %}
                <table>
                    <tr>
                        <td>Nama barang: </td>
                        <td><input type="text" name="nama_barang" placeholder="Nama barang" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td>Harga barang: </td>
                        <td><input type="number" name="harga_barang" placeholder="Harga barang" class="form-control"></td>
                    </tr>
        
                    <tr>
                        <td>Deskripsi: </td>
                        <td><input type="text" name="deskripsi" placeholder="Deskripsi barang" class="form-control"></td>
                    </tr>
        
                    <tr>
                        <td></td>
                        <td><input class="btn btn-primary" type="submit" value="Tambah"></td>
                    </tr>
                </table>
            </form>
        </div>
        
      </div>
    

    <div class="m-5 container text-center">
        <div class="row justify-content-md-center">
            <div class="col col-lg-10">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                          <th scope="col">Nama barang</th>
                          <th scope="col">Harga Barang</th>
                          <th scope="col">Deskripsi</th>
                        </tr>
                      </thead>
                    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
                    <tbody id="barang-wishlist">
                        {% for barang in list_barang %}
                            <tr>
                                <td>{{barang.nama_barang}}</td>
                                <td>{{barang.harga_barang}}</td>
                                <td>{{barang.deskripsi}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                   
                    </table>
            </div>
    
        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>
        {% endblock content %}
    </div>
</body>